### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'numel'

### ISSUE THREAD

**Issue by yutongo** [patrick-kidger/FasterNeuralDiffEq#2]
Hello,

So exited to see the improvement!
I tried to replace torchdiffeq with the suggested codes in the Summary but I got the error in 
make_norm
    state_size = state.numel():

'AttributeError: 'tuple' object has no attribute 'numel''

Any suggestions?

Thank you.

**Comment by patrick-kidger** [comment]
`torchdiffeq` now supports this option natively. Do `adjoint_options=dict(norm='seminorm')` instead.

**Comment by yutongo** [comment]
It works. Thank you!
